version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
              TERM: dumb
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: whatsapp-messager-{{ checksum "build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: whatsapp-messager-{{ checksum "build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew check
      - run:
          name: Save test results 
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ./build/libs
      - run:
          name: Build Artifacts
          command: ./gradlew assemble
      - persist_to_workspace:
          root: ~/
          paths: 
            - code
  deploy:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:8-jdk
    steps:      
      - attach_workspace:
          at: ~/
      - run:
          command: scp -o StrictHostKeyChecking=no -P $DEPLOYMENT_PORT ./build/libs/*.jar $DEPLOYMENT_URL
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build 
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "20 5 * * 5"
          filters:
            branches:
              only: 
                - master
    jobs:
      - build
